# Funding and Commercial Services
#
# GAP is open-source and free under Apache 2.0.
# Nexeom provides commercial implementation, consulting, and enterprise services.

custom:
  - https://nexeom.ca/gap
